version: '3.8'
services:
 
  backend:
    build: ./backend
    container_name: backend_innovatech
    ports:
      - "3001:3001"
    environment:
      DB_HOST: endpoint_rds_aqui
      DB_PASSWORD: admin123 
      DB_USER: root          
      DB_NAME: innovatech_ops
    networks:
      - red_devops

  frontend:
    build: ./frontend
    container_name: frontend_innovatech
    ports:
      - "80:80"
    networks:
      - red_devops

networks:
  red_devops:
    driver: bridge
    