version: '3.8'
services:
  bd:
    image: mysql:8.0
    container_name: bd_innovatech
    restart: always
    environment:
      MYSQL_DATABASE: innovatech_ops
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - db_data:/var/lib/mysql 
    networks:
      - red_devops

  backend:
    build: ./backend
    container_name: backend_innovatech
    ports:
      - "3001:3001"
    environment:
      DB_HOST: bd
      DB_PASSWORD: admin123 
      DB_USER: root          
      DB_NAME: innovatech_ops
    depends_on:
      - bd
    networks:
      - red_devops

  frontend:
    build: ./frontend
    container_name: frontend_innovatech
    ports:
      - "80:80"
    networks:
      - red_devops

networks:
  red_devops:
    driver: bridge

volumes:
  db_data: 